Repository applleeee/Lets-Git-It, pull requests merged in 2023-02, with the labels that each got.

#2 커뮤니티 글 생성[미완]
  .env.sample
  config/ormConfig.ts
  package-lock.json
  package.json
  src/community/community.controller.ts
  src/community/community.module.ts
  src/community/community.repository.ts
  src/community/community.service.ts
  src/community/dto/createPost.dto.ts
  src/community/entities/main_category.entity.ts
  src/community/entities/sub_category.entity.ts
  src/entities/Career.ts
  src/entities/Comment.ts
  src/entities/CommentLike.ts
  src/entities/Field.ts
  src/entities/MainCategory.ts
  src/entities/Post.ts
  src/entities/PostLike.ts
  src/entities/RankerProfile.ts
  src/entities/Ranking.ts
  src/entities/SubCategory.ts
  src/entities/Tier.ts
  src/entities/User.ts
  src/utiles/aws.ts
Labels: 추가 작업 중

#5 커뮤니티 글 좋아요 기능
  src/community/community.controller.ts
  src/community/community.repository.ts
  src/community/community.service.ts
  src/community/dto/createPost.dto.ts
  src/entities/PostLike.ts
Labels: 리뷰 요청

#6 add : 회원가입, 로그인 기능
  .env.sample
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/auth.transformer.ts
  src/auth/constants.ts
  src/auth/dto/auth.dto.ts
  src/auth/jwt.strategy.ts
  src/entities/Comment.ts
  src/entities/CommentLike.ts
  src/entities/Post.ts
  src/entities/PostLike.ts
  src/entities/RankerProfile.ts
  src/entities/User.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: 리뷰 요청, 질문 있음

#10 add: 유저의 post list, post like list 조회 로직(service,repository) 추가/ 상태유지정보
  src/community/community.repository.ts
  src/community/community.service.ts
Labels: 리뷰 완료, 질문 있음

#11 add: community comment 관련 api
  src/community/community.controller.ts
  src/community/community.module.ts
  src/community/community.repository.ts
  src/community/community.service.ts
  src/community/dto/comment.dto.ts
Labels: 리뷰 완료

#13 add: mypage 조회 / 수정 기능 구현
  src/auth/auth.module.ts
  src/community/community.module.ts
  src/community/community.repository.ts
  src/community/community.service.ts
  src/rank/rank.module.ts
  src/rank/rank_profile.repository.ts
  src/user/dto/mypage.dto.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: 리뷰 완료

#14 add : 토큰 검증 후 반환할 상태유지정보 추가
  src/auth/jwt.strategy.ts
  src/community/community.service.ts
Labels: 수정 요청

#18 refactor : 엄밀한 타입 정의
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/auth/jwt.strategy.ts
  src/community/community.controller.ts
  src/community/community.repository.ts
  src/community/community.service.ts
  src/community/dto/comment.dto.ts
  src/entities/Career.ts
  src/entities/Comment.ts
  src/entities/CommentLike.ts
  src/entities/Field.ts
  src/entities/MainCategory.ts
  src/entities/Post.ts
  src/entities/PostLike.ts
  src/entities/SubCategory.ts
  src/entities/User.ts
  src/user/dto/mypage.dto.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.service.ts
Labels: 리뷰 요청

#19 refactor : global error/exception filter
  src/app.module.ts
  src/main.ts
  src/utiles/http-exception.filter.ts
Labels: 리뷰 요청
